name: "Publish versioned artifacts"

on:
  push:
    tags: v*

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            nextroll/ecs-ship:v1
            nextroll/ecs-ship:v1.2
            nextroll/ecs-ship:v1.2.0
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  pre-release:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v4

      -
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      -
        name: Test
        run: go test -v ./...

      -
        name: Build
        run: CGO_ENABLED=0 go build -a -ldflags '-extldflags "-static"' .

      -
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: False
          files: |
            LICENSE
            ecs-ship
