name: "Publish latest artifacts"

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            nextroll/ecs-ship:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  pre-release:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2

      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      -
        name: Test
        run: go test -v ./...

      -
        name: Build
        run: CGO_ENABLED=0 go build -a -ldflags '-extldflags "-static"' .

      -
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE
            ecs-ship
